### PR TITLE
[FIX] CORS error in restaurant page

### LINKED ISSUE #123: [FIX] CORS error in restaurant page
- make api for calling recommend by restaurant so it fetch at server side
- change `getRecommendByRestaurant.ts` to call the created api

### PR DESCRIPTION
**Pull request by Sasirasys**
## Description

- fix: restaurant page cors error
- feat: add map icon besides restaurant name in dish detail page

## Changes Made

-

## Example Usage

-

```ts
// code here
```

## Related Issue

Closes #123

### CODE REVIEW

File: apps/web/src/app/api/recommend/restaurant/route.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+        JSON.stringify({
+          error: "Invalid request data",
+          details: parseData.error,
+        }),
+        { status: 400 },
+      );
+    }
+
+    const response = await fetch(
+      "https://calculories-ai-recommender.onrender.com/recommend/restaurant",
```
Comment (vinitian) [inline apps/web/src/app/api/recommend/restaurant/route.ts:76]: to be changed to env variable in the next issue

**Review by vinitian — APPROVED** [review]
